### ISSUE TITLE
执行找不到OpenVinoSharp.dll

### ISSUE THREAD

**Issue by QuietMinder** [guojin-yan/Csharp_and_OpenVINO_deploy_PaddleOCR#1]
你好 配置完成后可以生成OpenVinoSharp.dll,调用出错，无法找到改DLL.  需要复制哪些依赖dll吗？

**Comment by guojin-yan** [comment]
注意修改一下NativeMethods.cs文件中该dll文件的路径，该位置我采用的是绝对路径

**Comment by QuietMinder** [comment]
已经采用了绝对路径Unhandled exception. System.DllNotFoundException: Unable to load DLL 'E:\OpenVino\Csharp_and_OpenVINO_deploy_PaddleOCR\PaddleOCR文字识别\bin\Release\net6.0\OpenVinoSharp.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at OpenVinoSharpPaddleOCR.NativeMethods.core_init(String model_file, String device_name)
   at OpenVinoSharpPaddleOCR.PaddleOCR.paddleocr_openvino() in E:\OpenVino\Csharp_and_OpenVINO_deploy_PaddleOCR\PaddleOCR文字识别\PaddleOCR.cs:line 43
   at OpenVinoSharpPaddleOCR.Program.Main(String[] args) in E:\OpenVino\Csharp_and_OpenVINO_deploy_PaddleOCR\PaddleOCR文字识别\Program.cs:line 11

**Comment by guojin-yan** [comment]
你查看一下你的依赖项是否设置正确，openvino和opencv的，由于项目生成的是动态链接库，在生成时看不出来错误，在使用的时候会有错误。你可以尝试在生成dll的项目里，增加一个main函数，将项目改为生成exe文件，调用模型加载接口这个函数，看看是否有错误。

**Comment by QuietMinder** [comment]
配置了cv4.55 和 4.6都可以一次性生成dll,然后我该dll复制到C#生成的exe目录下 同时复制了openvino.dll和opencv_world460.dll 执行发现出错是在        
     public Core(string model_file, string device_name){
            // 初始化推理核心
            ptr = NativeMethods.core_init(model_file, device_name);  //这里错了 dll路径是对的
        }

**Comment by guojin-yan** [comment]
留个联系方式，我加你，给你远程一下
